version: "3.7"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - images-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: images

  nest-app:
    image: node:12-alpine
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - ./server/:/app
      - images-directory:/uploadedFiles
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: images

volumes:
  images-mysql-data:
  images-directory: